#
# This file is part of the Nuxo project.
#
# Copyright (c) 2025, Binary Shapes.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#

extends:
  - '../file-groups/src.yml'
  - '../internals/vite.yml'

tasks:
  build:
    extends: 'vite/build'
    deps:
      - 'lint'
      - 'format'
      - 'clean'
    options:
      internal: false
      mergeDeps: append
      runDepsInParallel: false
